In [1]:
import cv2
import os
import glob
import numpy as np
import matplotlib.pyplot as plt
import time as tm

In [2]:
train = "train"
split_img = "split_img"
os.system('rm -rf split_img')
try:
    os.mkdir(split_img)
except:
    garbage = 0


for i in range(65,91):
    try:
        os.mkdir(split_img + "/" + chr(i))
    except: 
        garbage = 0
       
captchas = glob.glob(os.path.join(train, "*"))


# count = np.zeros([256])
# captcha = "train/QDMK.png"
# img = cv2.imread(captcha,0)

# cv2.imshow('image',img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

# for i in range(len(img)) :  
#     for j in range(len(img[i])) :  
#         count[img[i][j]] += 1
# sort_count = np.sort(count)
# sort_ind = np.argsort(count)[-20:-1]
# print(sort_ind)

# for i in range(len(img)) :  
#     for j in range(len(img[i])) :  
#         flag = 0
#         for k in sort_ind :
#             if(img[i][j] == k) :
#                 flag = 1
#                 break
#         if(flag == 1):
#             img[i][j] = 0
#         else:
#             img[i][j] = 255
            
# cv2.imshow('image',img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
tic = tm.perf_counter()

count = 0
for (i, captcha) in enumerate(captchas):
#     captcha = "train/EGN.png"
#     print(captcha,i)
    img = cv2.imread(captcha)   #read image as grayscale
    print(captcha)
#     cv2.imshow('image',img)
#     cv2.waitKey(0)
#     cv2.destroyAllWindows()
    
    first_px = img[0,0]
    img[np.where(img == first_px)] = 0
    
    kernel = np.ones((6,6),np.uint8)
    erosion = cv2.erode(img, kernel, iterations = 1)  
    img = cv2.morphologyEx(erosion, cv2.MORPH_OPEN, kernel)
    #dilation = cv2.dilate(img,kernel,iterations = 1)
#     img=erosion
    img[np.where(img == 0)] = 255
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    img[np.where(img != 255)] = 0
    
    crop_s = []
    crop_e = []
    
    start = 0
    end = 0
    flag = 1
    
    
    img = np.transpose(img)
    
    #print(len(img))
    
    num_px = 0 # number of pixels
    
    for i in range(len(img)):
        if  flag and np.sum(img[i]) != 255*(len(img[i])) :
            start = i
            flag = 0
        elif flag == 0 and np.sum(img[i]) == 255*(len(img[i])) :
            flag = 1;
            mid = int((i + start)/2)
            if i - start > 25 and np.sum(img[mid])<(255*(len(img[mid])-10)):
                crop_s.append(start)
                crop_e.append(i)
    #print(crop)
    
    img = np.transpose(img)
#     cv2.imshow('image',img)
#     cv2.waitKey(0)
#     cv2.destroyAllWindows()
    filename = os.path.basename(captcha)
    captcha_text = os.path.splitext(filename)[0]
    if (len(crop_s)-len(captcha_text)) != 0 :
        print(captcha_text)
        print(len(crop_s))
        print(len(captcha_text))
    for i in range(len(crop_s)):
        if i == len(captcha_text):
            break
        x_ = crop_s[i]
        y_ = crop_e[i]
        crop_img = img[:,x_-5:y_+5]
        save_path = os.path.join(split_img, captcha_text[i])
        p = os.path.join(save_path, "{}.png".format(str(count)))
        cv2.imwrite(p, crop_img)
        count += 1
        
#         cv2.imshow(captcha_text[i] + ".png", crop_img)
#         cv2.waitKey(0)
#         cv2.destroyAllWindows()
#     break

toc = tm.perf_counter()
print(toc-tic)

train/FBF.png
train/EPOV.png
train/MDN.png
train/KQH.png
train/PFNO.png
train/LCH.png
train/PFU.png
train/RQO.png
train/GMMU.png
train/XQO.png
train/AING.png
train/TNZJ.png
train/TNG.png
train/CJF.png
train/QUM.png
train/GYZ.png
train/OWFW.png
train/GYY.png
train/HLR.png
train/ACF.png
train/RSKC.png
train/LYL.png
train/PIPI.png
train/TSNL.png
train/TRWJ.png
train/SYL.png
train/MDA.png
train/FLTG.png
train/MVKF.png
train/WJMM.png
train/SKNM.png
train/FZW.png
train/NIS.png
train/PJYZ.png
train/LGX.png
train/MHRB.png
train/VYYQ.png
train/ILY.png
train/GJMV.png
train/HEPH.png
train/RBG.png
train/SMC.png
train/RDSQ.png
train/JGO.png
train/HDR.png
train/XBHU.png
train/ATZ.png
train/WBSD.png
train/DEM.png
train/KBHZ.png
train/AGZF.png
train/JLIV.png
train/TAAV.png
train/HBNV.png
train/LLEK.png
train/EXI.png
train/LOYD.png
train/FVN.png
train/LKWW.png
train/CHYR.png
train/IRZ.png
train/KHN.png
train/ONPK.png
train/HDOO.png
train/NLJC.png
train/NLRN.png
train/VHOJ.png
train/DIBZ.png
train/XKR.p

train/AQVU.png
train/XQIT.png
train/GUL.png
train/WDZ.png
train/HOJ.png
train/ISXL.png
train/DYE.png
train/FWT.png
train/QNP.png
train/LCKZ.png
train/PJLH.png
train/OXPU.png
train/TFX.png
train/XAC.png
train/CSB.png
train/VSW.png
train/MVAZ.png
train/MLAF.png
train/QNJ.png
train/LBX.png
train/VZQH.png
train/OIDT.png
train/NPM.png
train/LBXX.png
train/LAC.png
train/HBNI.png
train/COI.png
train/OAT.png
train/QXW.png
train/VKQ.png
train/FHLQ.png
train/XOZ.png
train/QRX.png
train/PTCP.png
train/WUT.png
train/DRYI.png
train/LWD.png
train/DUJ.png
train/CXGJ.png
train/AJMN.png
train/PZEC.png
train/NUQ.png
train/BLXL.png
train/OUO.png
train/QQO.png
train/TYTB.png
train/AQO.png
train/OCGN.png
train/MVW.png
train/JIQR.png
train/CKE.png
train/KWZX.png
train/WDOU.png
train/AAA.png
train/DST.png
train/GTS.png
train/SSVB.png
train/QQM.png
train/HZKQ.png
train/VFDO.png
train/NOE.png
train/EYIZ.png
train/NKV.png
train/PHIP.png
train/EKM.png
train/RJBP.png
train/IOK.png
train/AHCD.png
train/RPFB.png
tr

train/MJNU.png
train/BCQ.png
train/BWE.png
train/KAF.png
train/RUQ.png
train/HXV.png
train/PDXG.png
train/NXO.png
train/XPD.png
train/QLCT.png
train/XNV.png
train/KODQ.png
train/JSD.png
train/BCEM.png
train/OZSD.png
train/UCS.png
train/QIQT.png
train/CPSB.png
train/LRL.png
train/FUC.png
train/KWOF.png
train/XMMG.png
train/RVQ.png
train/RSDG.png
train/BGUB.png
train/PIOO.png
train/KBF.png
train/NTL.png
train/WOO.png
train/CEH.png
train/VNMP.png
train/BOZ.png
train/BUF.png
train/RME.png
train/LDMT.png
train/FHNS.png
train/KDEJ.png
train/PMT.png
train/EPMU.png
train/FUYH.png
train/FKPX.png
train/ARFQ.png
train/LCWF.png
train/DBRW.png
train/CXW.png
train/IQW.png
train/DXQL.png
train/NVPD.png
train/WGL.png
train/RHTJ.png
train/KDIA.png
train/OZLS.png
train/XOX.png
train/QPAP.png
train/NYN.png
train/HDNW.png
train/IVQ.png
train/PYBW.png
train/XQY.png
train/ONR.png
train/CPO.png
train/WOP.png
train/VCS.png
train/FQIV.png
train/XTA.png
train/AGIA.png
train/UOTE.png
train/QGP.png
train/QARO.png

In [6]:
# training a model 
X = []
y = []
solved_letters = glob.glob(os.path.join("split_img/*", "*"))
for i,img in enumerate(solved_letters):
    try:
        txt = img.split('/')[1]
#         yi =np.zeros(26)
#         yi[ord(txt)-65] =1
#             print(img)
        yi = ord(txt)-65
        img = cv2.imread(img,0)
        dim = (28,28)
        img = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
        img = img.reshape(-1)
        X.append(np.array(img))
        y.append(yi)
#         print(img.shape)
#         break
    except:
        print("Not a image")



In [7]:
X = np.array(X)
y = np.array(y)
print(X.shape)
print(y.shape)

(7006, 784)
(7006,)


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
print(X_train)


[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [17]:
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
# Normalizing the RGB codes by dividing it to the max RGB value.
X_train /= 255
X_test /= 255

In [10]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D
# Creating a Sequential Model and adding the layers
input_shape = (28, 28, 1)
model = Sequential()
model.add(Conv2D(28, kernel_size=(3,3), input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten()) # Flattening the 2D arrays for fully connected layers
model.add(Dense(128, activation=tf.nn.relu))
model.add(Dropout(0.2))
model.add(Dense(26,activation=tf.nn.softmax))
model.summary()

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 28)        280       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 13, 13, 28)        0         
_________________________________________________________________
flatten (Flatten)            (None, 4732)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               605824    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 26)                3354      
Total params: 609,458
Trainable params: 6

In [20]:

model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
model.fit( X_train, y_train, epochs=5)

Train on 5604 samples
Epoch 1/5
5604/5604 [==============================] - 4s 747us/sample - loss: 0.0223 - acc: 0.9938
Epoch 2/5
5604/5604 [==============================] - 4s 691us/sample - loss: 0.0222 - acc: 0.9939
Epoch 3/5
5604/5604 [==============================] - 4s 687us/sample - loss: 0.0204 - acc: 0.9938
Epoch 4/5
5604/5604 [==============================] - 4s 684us/sample - loss: 0.0184 - acc: 0.9955
Epoch 5/5
5604/5604 [==============================] - 4s 700us/sample - loss: 0.0134 - acc: 0.9975


In [21]:
tic = tm.perf_counter()
model.evaluate(X_test, y_test)
# model.evaluate(X_train, y_train)
toc = tm.perf_counter()

print( "Total time taken is %.6f seconds " % (toc - tic) )

1402/1402 [==============================] - 1s 404us/sample - loss: 0.0070 - acc: 0.9986
Total time taken is 0.589142 seconds 


In [22]:
model.save("model.h5")